[package]
name = "arewegameyet"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>", "doppioslash"]

[dependencies]
reqwest = "0.7.2"
toml = "0.4.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.2"